apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: springfluxapp-policy
  namespace: default
spec:
  filterTags:
    pattern: '^latest$'
  policy:
    semver:
      range: '>=0.0.1'
