apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: springfluxapp-kustomization
  namespace: default
spec:
  interval: 1m
  path: ./k8s
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: springfluxapp-repo
